site_name: EasyRunner
site_url: https://docs.easyrunner.xyz
site_description: EasyRunner Content
copyright: Copyright &copy; 2025 Janaka Abeywardhana
theme:
  name: material
  features:
    - navigation.footer  
  font:
    text: Roboto Mono
    code: Roboto Mono
  palette:
    - scheme: default
      primary: custom
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: custom
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  custom_dir: docs/stylesheets
  favicon: images/favicon.svg
  logo: images/logo.png
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - social
  - blog:
      blog_dir: blog
      post_dir: blog/posts
      post_excerpt: required
      blog_toc: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/janaka
    - icon: fontawesome/brands/square-x-twitter
      link: https://x.com/janaka_a